before_script:
    - python setup.py install

### local
customassert_debug:
    script: "python2 tests/test_exceptions.py"
    tags: [angr]

customassert_optimized:
    script: "python2 -O tests/test_exceptions.py"
    tags: [angr]

